services:

  mysql:
    image: mysql:8
    container_name: hrms-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hrms_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: hrms-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JWT_SECRET: mysecretkeymysecretkeymysecretkeymysecretkey
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hrms_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"

volumes:
  mysql_data:
