# ===============================
# DATASOURCE (Read from Docker ENV)
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# ===============================
# JWT
# ===============================
jwt.secret=${JWT_SECRET}

# ===============================
# Logging
# ===============================
logging.level.root=WARN
logging.file.name=logs/hrms-prod.log

# ===============================
# Production Security Hardening
# ===============================
server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never
