spring.profiles.active=prod

# JWT (environment variable fallback)
jwt.secret=${JWT_SECRET:mysecretkeymysecretkeymysecretkeymysecretkey}
jwt.access-expiration=900000
jwt.refresh-expiration=86400000

# Server Port (common)
server.port=8080

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=HRMS Backend
info.app.version=1.0
info.app.description=Enterprise HRMS System